client_id = "c4aa521b743779cc485898c2803f6480"
name = "Neryn"
handle = "neryn"
application_url = "https://neryn.pro/shopify/auth"
embedded = true

[access_scopes]
scopes = "read_customer_events,read_cart_transforms,write_cart_transforms,read_customers,write_customers,read_inventory,read_orders,write_orders,read_product_listings,write_product_listings,read_products,write_products,read_script_tags,write_script_tags,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_tags"

[auth]
redirect_urls = [
  "https://neryn.pro/api/shopify/callback"
]

[webhooks]
api_version = "2025-01"

  [webhooks.privacy_compliance]
  customer_data_request_url = "https://neryn.pro/api/webhooks/shopify"
  customer_deletion_url = "https://neryn.pro/api/webhooks/shopify"
  shop_deletion_url = "https://neryn.pro/api/webhooks/shopify"

  [[webhooks.subscriptions]]
  topics = [
    "app/uninstalled",
    "app_subscriptions/update"
  ]
  uri = "https://neryn.pro/api/webhooks/shopify"

  [[webhooks.subscriptions]]
  topics = [
    "products/create",
    "products/update",
    "products/delete"
  ]
  uri = "https://neryn.pro/api/webhooks/shopify"

  [[webhooks.subscriptions]]
  topics = [
    "orders/create",
    "orders/updated"
  ]
  uri = "https://neryn.pro/api/webhooks/shopify"

  [[webhooks.subscriptions]]
  topics = [
    "customers/create",
    "customers/update"
  ]
  uri = "https://neryn.pro/api/webhooks/shopify"

  [[webhooks.subscriptions]]
  topics = [
    "inventory_levels/update"
  ]
  uri = "https://neryn.pro/api/webhooks/shopify"

[pos]
embedded = false
